/**
 * shared/productCatalog.js — TRIVERSE Product Preset Catalog
 * 20 furniture products used by the ML recommendation engine.
 * All GLBs are from KhronosGroup sample models (free, public).
 * Dual export: CommonJS (backend) + browser global (frontend).
 */

const GLB = {
  sofa:  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb',
  chair: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/SheenChair/glTF-Binary/SheenChair.glb',
  lamp:  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/IridescenceLamp/glTF-Binary/IridescenceLamp.glb',
  misc:  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb',
};

const PRODUCT_CATALOG = [
  {
    id: 'sofa-modern-01',
    name: 'Wakefit Orthopaedic 3-Seater Sofa',
    category: 'sofa', styles: ['modern', 'minimalist'],
    roomTypes: ['living', 'studio'],
    price_inr: 24999,
    imageUrl: 'https://picsum.photos/seed/sofa1/400/280',
    glbUrl: GLB.sofa,
    dimensions: { lengthCm: 210, widthCm: 85, heightCm: 90 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=wakefit+sofa',
    tags: ['3-seater', 'fabric', 'orthopedic'],
  },
  {
    id: 'sofa-compact-02',
    name: 'Urban Ladder 2-Seater Loveseat',
    category: 'sofa', styles: ['modern', 'scandinavian'],
    roomTypes: ['living', 'studio', 'bedroom'],
    price_inr: 15999,
    imageUrl: 'https://picsum.photos/seed/sofa2/400/280',
    glbUrl: GLB.sofa,
    dimensions: { lengthCm: 150, widthCm: 80, heightCm: 85 },
    platform: 'Flipkart',
    buyUrl: 'https://www.flipkart.com/search?q=2+seater+sofa',
    tags: ['2-seater', 'compact', 'loveseat'],
  },
  {
    id: 'sofa-luxury-03',
    name: 'Nilkamal L-Shaped Corner Sofa',
    category: 'sofa', styles: ['modern', 'traditional'],
    roomTypes: ['living'],
    price_inr: 54999,
    imageUrl: 'https://picsum.photos/seed/sofa3/400/280',
    glbUrl: GLB.sofa,
    dimensions: { lengthCm: 280, widthCm: 180, heightCm: 90 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=l+shaped+sofa',
    tags: ['l-shaped', 'corner', 'premium'],
  },
  {
    id: 'chair-accent-04',
    name: 'Featherlite Accent Arm Chair',
    category: 'chair', styles: ['modern', 'scandinavian', 'minimalist'],
    roomTypes: ['living', 'bedroom', 'study'],
    price_inr: 8999,
    imageUrl: 'https://picsum.photos/seed/chair1/400/280',
    glbUrl: GLB.chair,
    dimensions: { lengthCm: 70, widthCm: 70, heightCm: 85 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=accent+chair',
    tags: ['accent', 'arm-chair', 'fabric'],
  },
  {
    id: 'chair-recliner-05',
    name: 'Durian Recliner Lounge Chair',
    category: 'chair', styles: ['traditional', 'modern'],
    roomTypes: ['living', 'bedroom'],
    price_inr: 22999,
    imageUrl: 'https://picsum.photos/seed/chair2/400/280',
    glbUrl: GLB.chair,
    dimensions: { lengthCm: 90, widthCm: 85, heightCm: 100 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=recliner+chair',
    tags: ['recliner', 'lounge', 'premium'],
  },
  {
    id: 'chair-study-06',
    name: 'Green Soul Ergonomic Study Chair',
    category: 'chair', styles: ['minimalist', 'modern', 'industrial'],
    roomTypes: ['study'],
    price_inr: 6999,
    imageUrl: 'https://picsum.photos/seed/chair3/400/280',
    glbUrl: GLB.chair,
    dimensions: { lengthCm: 60, widthCm: 60, heightCm: 110 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=ergonomic+chair',
    tags: ['ergonomic', 'study', 'office'],
  },
  {
    id: 'table-center-07',
    name: 'Wooden Street Sheesham Center Table',
    category: 'table', styles: ['traditional', 'bohemian', 'modern'],
    roomTypes: ['living'],
    price_inr: 9999,
    imageUrl: 'https://picsum.photos/seed/table1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 120, widthCm: 60, heightCm: 45 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=center+table+wood',
    tags: ['wood', 'center-table', 'sheesham'],
  },
  {
    id: 'table-dining-08',
    name: 'Godrej Interio 6-Seater Dining Table',
    category: 'table', styles: ['modern', 'minimalist'],
    roomTypes: ['dining'],
    price_inr: 32999,
    imageUrl: 'https://picsum.photos/seed/table2/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 180, widthCm: 90, heightCm: 75 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=dining+table+6+seater',
    tags: ['dining', '6-seater', 'wood'],
  },
  {
    id: 'table-study-09',
    name: 'Zuari Height-Adjustable Study Desk',
    category: 'table', styles: ['minimalist', 'modern', 'industrial'],
    roomTypes: ['study', 'kids'],
    price_inr: 12999,
    imageUrl: 'https://picsum.photos/seed/table3/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 120, widthCm: 60, heightCm: 75 },
    platform: 'Flipkart',
    buyUrl: 'https://www.flipkart.com/search?q=study+desk',
    tags: ['desk', 'height-adjustable', 'study'],
  },
  {
    id: 'table-side-10',
    name: 'Pepperfry Bedside Table with Drawer',
    category: 'table', styles: ['modern', 'minimalist', 'scandinavian'],
    roomTypes: ['bedroom', 'any'],
    price_inr: 3999,
    imageUrl: 'https://picsum.photos/seed/table4/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 45, widthCm: 40, heightCm: 55 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=bedside+table',
    tags: ['bedside', 'drawer', 'compact'],
  },
  {
    id: 'lamp-floor-11',
    name: 'Solimo Floor Lamp with Tripod',
    category: 'lamp', styles: ['modern', 'industrial', 'scandinavian'],
    roomTypes: ['living', 'bedroom', 'study'],
    price_inr: 3499,
    imageUrl: 'https://picsum.photos/seed/lamp1/400/280',
    glbUrl: GLB.lamp,
    dimensions: { lengthCm: 40, widthCm: 40, heightCm: 150 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=floor+lamp+tripod',
    tags: ['floor-lamp', 'tripod', 'ambient'],
  },
  {
    id: 'lamp-pendant-12',
    name: 'Craftter Rattan Pendant Lamp',
    category: 'lamp', styles: ['bohemian', 'traditional', 'industrial'],
    roomTypes: ['dining', 'living', 'study'],
    price_inr: 4999,
    imageUrl: 'https://picsum.photos/seed/lamp2/400/280',
    glbUrl: GLB.lamp,
    dimensions: { lengthCm: 40, widthCm: 40, heightCm: 60 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=rattan+pendant+lamp',
    tags: ['pendant', 'rattan', 'bohemian'],
  },
  {
    id: 'bed-queen-13',
    name: 'Wakefit Queen Bed with Storage',
    category: 'bed', styles: ['modern', 'minimalist'],
    roomTypes: ['bedroom'],
    price_inr: 22999,
    imageUrl: 'https://picsum.photos/seed/bed1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 210, widthCm: 165, heightCm: 95 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=queen+bed+with+storage',
    tags: ['queen', 'storage', 'hydraulic'],
  },
  {
    id: 'bed-single-14',
    name: 'Nilkamal Single Bed with Drawer',
    category: 'bed', styles: ['minimalist', 'scandinavian'],
    roomTypes: ['bedroom', 'kids'],
    price_inr: 12999,
    imageUrl: 'https://picsum.photos/seed/bed2/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 200, widthCm: 110, heightCm: 85 },
    platform: 'Flipkart',
    buyUrl: 'https://www.flipkart.com/search?q=single+bed',
    tags: ['single', 'drawer', 'wood'],
  },
  {
    id: 'storage-shelf-15',
    name: 'Bluewud 5-Tier Bookshelf',
    category: 'storage', styles: ['scandinavian', 'minimalist', 'modern'],
    roomTypes: ['study', 'living', 'any'],
    price_inr: 7999,
    imageUrl: 'https://picsum.photos/seed/shelf1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 60, widthCm: 30, heightCm: 180 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=bookshelf+5+tier',
    tags: ['bookshelf', '5-tier', 'display'],
  },
  {
    id: 'storage-wardrobe-16',
    name: 'Godrej Slimline 3-Door Wardrobe',
    category: 'storage', styles: ['modern', 'minimalist'],
    roomTypes: ['bedroom'],
    price_inr: 28999,
    imageUrl: 'https://picsum.photos/seed/wardrobe1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 150, widthCm: 55, heightCm: 195 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=3+door+wardrobe',
    tags: ['wardrobe', '3-door', 'mirror'],
  },
  {
    id: 'storage-tv-17',
    name: 'Wooden Street TV Unit with Shelves',
    category: 'storage', styles: ['modern', 'industrial'],
    roomTypes: ['living'],
    price_inr: 15999,
    imageUrl: 'https://picsum.photos/seed/tvunit1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 150, widthCm: 40, heightCm: 55 },
    platform: 'Flipkart',
    buyUrl: 'https://www.flipkart.com/search?q=tv+unit',
    tags: ['tv-unit', 'shelves', 'wood'],
  },
  {
    id: 'decor-ottoman-18',
    name: 'Solimo Round Fabric Ottoman',
    category: 'decor', styles: ['bohemian', 'modern', 'traditional'],
    roomTypes: ['living', 'bedroom', 'any'],
    price_inr: 2999,
    imageUrl: 'https://picsum.photos/seed/ottoman1/400/280',
    glbUrl: GLB.chair,
    dimensions: { lengthCm: 50, widthCm: 50, heightCm: 40 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=round+ottoman',
    tags: ['ottoman', 'round', 'fabric'],
  },
  {
    id: 'decor-plant-19',
    name: 'Decorative Bamboo Plant Stand',
    category: 'decor', styles: ['bohemian', 'scandinavian', 'minimalist'],
    roomTypes: ['balcony', 'living', 'any'],
    price_inr: 1999,
    imageUrl: 'https://picsum.photos/seed/plant1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 40, widthCm: 40, heightCm: 90 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=plant+stand+bamboo',
    tags: ['plant-stand', 'bamboo', 'decor'],
  },
  {
    id: 'decor-wall-shelf-20',
    name: 'Ferns N Petals Floating Wall Shelf Set',
    category: 'storage', styles: ['modern', 'minimalist', 'industrial'],
    roomTypes: ['any'],
    price_inr: 3499,
    imageUrl: 'https://picsum.photos/seed/wallshelf1/400/280',
    glbUrl: GLB.misc,
    dimensions: { lengthCm: 60, widthCm: 20, heightCm: 15 },
    platform: 'Amazon India',
    buyUrl: 'https://www.amazon.in/s?k=floating+wall+shelf',
    tags: ['wall-shelf', 'floating', 'set'],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCT_CATALOG };
} else if (typeof window !== 'undefined') {
  window.PRODUCT_CATALOG = PRODUCT_CATALOG;
}
